# Generated by Django 5.2.7 on 2025-10-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_plaque', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('type_vehicule', models.CharField(choices=[('camion_benne', 'Camion à benne'), ('camion_compacteur', 'Camion compacteur'), ('camionnette', 'Camionnette'), ('tracteur', 'Tracteur')], max_length=20)),
                ('capacite_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacite_volume', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('operationnel', 'Opérationnel'), ('maintenance', 'En maintenance'), ('panne', 'En panne'), ('reforme', 'Réformé')], default='operationnel', max_length=15)),
                ('kilometrage', models.IntegerField(default=0)),
                ('derniere_revision', models.DateField(blank=True, null=True)),
                ('prochaine_revision', models.DateField(blank=True, null=True)),
                ('numero_assurance', models.CharField(blank=True, max_length=50)),
                ('expiration_assurance', models.DateField(blank=True, null=True)),
                ('expiration_controle_technique', models.DateField(blank=True, null=True)),
                ('equipements', models.JSONField(default=list)),
                ('consommation_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['numero_plaque'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('poste', models.CharField(choices=[('chauffeur', 'Chauffeur'), ('collecteur', 'Collecteur'), ('chef_equipe', "Chef d'équipe"), ('superviseur', 'Superviseur')], max_length=20)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'En congé'), ('maladie', 'Maladie'), ('formation', 'En formation')], default='actif', max_length=10)),
                ('date_embauche', models.DateField()),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=50)),
                ('numero_permis', models.CharField(blank=True, max_length=50)),
                ('type_permis', models.CharField(blank=True, max_length=10)),
                ('date_expiration_permis', models.DateField(blank=True, null=True)),
                ('certifications', models.JSONField(default=list)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=100)),
                ('contact_urgence_phone', models.CharField(blank=True, max_length=20)),
                ('contact_urgence_relation', models.CharField(blank=True, max_length=50)),
                ('note_evaluation', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('derniere_evaluation', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('zone_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_principaux', to='clients.zonecollecte')),
                ('zones_affectees', models.ManyToManyField(blank=True, to='clients.zonecollecte')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipe', models.CharField(max_length=100)),
                ('jours_travail', models.JSONField(default=list)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_equipe', models.ForeignKey(limit_choices_to={'poste': 'chef_equipe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_dirigees', to='agents.agent')),
                ('membres', models.ManyToManyField(related_name='equipes', to='agents.agent')),
                ('zones_intervention', models.ManyToManyField(to='clients.zonecollecte')),
                ('vehicule_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.vehicule')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['nom_equipe'],
            },
        ),
    ]
