# Generated by Django 5.2.7 on 2025-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='poste',
            field=models.CharField(choices=[('collecteur_argent', "Collecteur d'argent"), ('ramasseur_ordures', "Ramasseur d'ordures"), ('superviseur', 'Superviseur'), ('agent_prospection', 'Agent de prospection'), ('chauffeur', 'Chauffeur')], max_length=30),
        ),
    ]
