# Generated by Django 5.2.7 on 2025-10-18 21:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('periode_facturation', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=15)),
                ('date_debut_periode', models.DateField()),
                ('date_fin_periode', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_passages_prevu', models.IntegerField()),
                ('nombre_passages_realise', models.IntegerField(default=0)),
                ('quantite_collectee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('partiellement_payee', 'Partiellement payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('date_paiement_complet', models.DateTimeField(blank=True, null=True)),
                ('generee_automatiquement', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.contrat')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paiement', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire'), ('mypay_bf', 'MyPayBF (en ligne)'), ('abonnement_prepaye', 'Abonnement prépayé')], max_length=20)),
                ('qr_code_utilise', models.CharField(blank=True, max_length=100)),
                ('qr_code_valide', models.BooleanField(default=False)),
                ('latitude_paiement', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude_paiement', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('numero_cheque', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('en_verification', 'En vérification (48h)'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField()),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('valide_par_client', models.BooleanField(default=False)),
                ('date_validation_client', models.DateTimeField(blank=True, null=True)),
                ('conteste_par_client', models.BooleanField(default=False)),
                ('motif_contestation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_collecteur', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'agent_collecte'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_collectes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='paiements.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True)),
                ('type_recu', models.CharField(choices=[('numerique', 'Numérique'), ('papier', 'Papier'), ('sms', 'SMS'), ('email', 'Email')], max_length=15)),
                ('contenu_recu', models.JSONField()),
                ('signature_numerique', models.TextField(blank=True)),
                ('envoye', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('destinataire_email', models.EmailField(blank=True, max_length=254)),
                ('destinataire_sms', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RapportPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField()),
                ('nombre_paiements', models.IntegerField(default=0)),
                ('montant_total_collecte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('montant_especes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('montant_mobile_money', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transmis_admin', models.BooleanField(default=False)),
                ('date_transmission', models.DateTimeField(blank=True, null=True)),
                ('valide_par_admin', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_collecteur', models.ForeignKey(limit_choices_to={'user_type': 'agent_collecte'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone_collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.zonecollecte')),
            ],
            options={
                'verbose_name': 'Rapport de paiement',
                'verbose_name_plural': 'Rapports de paiement',
                'ordering': ['-date_rapport'],
                'unique_together': {('agent_collecteur', 'date_rapport')},
            },
        ),
    ]
