# Generated by Django 5.2.7 on 2025-10-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_passage_prevue', models.TimeField()),
                ('ordre_passage', models.IntegerField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('completee', 'Complétée'), ('ratee', 'Ratée'), ('reportee', 'Reportée')], default='planifiee', max_length=15)),
                ('types_dechets_collectes', models.JSONField(default=list)),
                ('quantite_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nombre_contenants', models.IntegerField(default=0)),
                ('raison_echec', models.CharField(blank=True, choices=[('client_absent', 'Client absent'), ('acces_bloque', 'Accès bloqué'), ('pas_de_dechets', 'Pas de déchets'), ('vehicule_plein', 'Véhicule plein'), ('probleme_technique', 'Problème technique'), ('autre', 'Autre')], max_length=20)),
                ('details_echec', models.TextField(blank=True)),
                ('signature_client', models.TextField(blank=True)),
                ('nom_signataire', models.CharField(blank=True, max_length=100)),
                ('latitude_collecte', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude_collecte', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('photo_avant', models.ImageField(blank=True, null=True, upload_to='collectes/photos/')),
                ('photo_apres', models.ImageField(blank=True, null=True, upload_to='collectes/photos/')),
                ('notes_agent', models.TextField(blank=True)),
                ('commentaire_client', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Collecte',
                'verbose_name_plural': 'Collectes',
                'ordering': ['tournee', 'ordre_passage'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamation', models.CharField(max_length=20, unique=True)),
                ('type_reclamation', models.CharField(choices=[('collecte_manquee', 'Collecte manquée'), ('collecte_incomplete', 'Collecte incomplète'), ('retard', 'Retard important'), ('dommage', 'Dommage matériel'), ('comportement', 'Comportement agent'), ('qualite_service', 'Qualité du service'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('status', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_traitement', 'En traitement'), ('resolue', 'Résolue'), ('fermee', 'Fermée')], default='ouverte', max_length=15)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('actions_correctives', models.TextField(blank=True)),
                ('note_satisfaction', models.IntegerField(blank=True, null=True)),
                ('commentaire_resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigne_a', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='collectes.collecte')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tournee', models.CharField(max_length=100)),
                ('date_tournee', models.DateField()),
                ('heure_debut_prevue', models.TimeField()),
                ('heure_fin_prevue', models.TimeField()),
                ('heure_debut_reelle', models.TimeField(blank=True, null=True)),
                ('heure_fin_reelle', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='planifiee', max_length=15)),
                ('nombre_clients_prevus', models.IntegerField(default=0)),
                ('nombre_clients_realises', models.IntegerField(default=0)),
                ('distance_parcourue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carburant_consomme', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('problemes_rencontres', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipe_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.equipe')),
                ('vehicule_assigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.vehicule')),
                ('zone_collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.zonecollecte')),
            ],
            options={
                'verbose_name': 'Tournée',
                'verbose_name_plural': 'Tournées',
                'ordering': ['-date_tournee', 'heure_debut_prevue'],
            },
        ),
        migrations.AddField(
            model_name='collecte',
            name='tournee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectes', to='collectes.tournee'),
        ),
    ]
